services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3001:4000"
    environment:
      - REDIS_URL=redis://redis01:6379
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
  redis:
    image: redis/redis-stack:latest
    container_name: lab-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - /home/user/Documents/redis_data:/data